version: '3'

services:
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/etc/trino
      - ./plugin:/usr/lib/trino/plugin
      - ./dados:/data
